name: formatter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Format
        run: npm run format

      - name: Lint SCSS
        run: npm run lint:scss:fix

      - name: Lint Astro
        run: npm run lint:fix
